apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "janus-cryptobom.fullname" . }}-config
  labels:
    app.kubernetes.io/name: {{ include "janus-cryptobom.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
data:
  JANUS_HTTP_ADDR: "0.0.0.0:{{ .Values.server.port }}"
  JANUS_GRPC_ADDR: "0.0.0.0:{{ .Values.server.grpcPort }}"
  JANUS_LOG_LEVEL: "{{ .Values.server.logLevel }}"
  JANUS_DISABLE_AUTH: "{{ .Values.server.disableAuth }}"
  JANUS_DB_MAX_CONNS: "25"
  JANUS_DB_MIN_CONNS: "5"
  JANUS_AGENT_STALL_SECONDS: "300"
  JANUS_CORS_ORIGIN: "http://localhost:5173"
  JANUS_SCAN_SCHEDULE: "{{ .Values.agent.scan.schedule }}"
  JANUS_MIN_KEY_SIZE: "{{ .Values.agent.scan.minKeySize }}"
  JANUS_EXCLUDE_DIRS: "{{ .Values.agent.scan.excludeDirs }}"
  JANUS_RETENTION_DAYS: "{{ .Values.retention.days }}"
  JANUS_AUTO_PURGE: "{{ .Values.retention.autoPurge }}"
